name: Build artifacts

on:
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - uses: actions/checkout@v2
      - name: install os deps
        run: |
          apt-get -qq update && apt-get -qy install rpm fakeroot
      - name: install lein deps
        run: |
          lein install
      - name: install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - name: install node.js
        run: |
          export NVM_DIR=$HOME/.nvm && . "$NVM_DIR/nvm.sh" && nvm install v12.16.3
      - name: get node deps
        run: |
          npm install
      - name: build static - clj->js
        run: |
          lein cljsbuild once prerender
      - name: build static - js->html
        run: |
          node target/cljsbuild/prerender/main.js target/cljsbuild/prod-static/public/
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: artifacts
      #     path: |
      #       ./target/*.deb
      #       ./target/*.rpm
      #       ./target/*.md5
      #       ./target/*.jar
      #       ./target/*.bz2
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: ${{ github.event.release.tag_name }}
      #   with:
      #     name: artifacts
      #     draft: true
      #     files: ./target/*${{ github.event.release.tag_name }}*
