name: Build artifacts

on:
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - uses: actions/checkout@v2
      - name: install os deps
        run: |
          apt-get -qq update && apt-get -qy install rpm fakeroot
      - name: install lein deps
        run: |
          lein install
      - name: install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - name: install node.js
        run: |
          export NVM_DIR=$HOME/.nvm && . "$NVM_DIR/nvm.sh" && nvm install v19.6.1
      - name: get node deps
        run: |
          export NVM_DIR=$HOME/.nvm && . "$NVM_DIR/nvm.sh" && npm install
      - name: build static - clj->js (js builder script)
        run: |
          export NVM_DIR=$HOME/.nvm && . "$NVM_DIR/nvm.sh" && lein cljsbuild once prerender
      - name: build static - js->html
        run: |
          export NVM_DIR=$HOME/.nvm && . "$NVM_DIR/nvm.sh" && node target/cljsbuild/prerender/main.js target/cljsbuild/prod-static/public/
      - name: make archive - js builder script
        run: |
          tar -czvf static-js-builder.tar.gz -C target/cljsbuild/prerender/ .
      - name: make archive - static site
        run: |
          tar -czvf static.tar.gz -C target/cljsbuild/prod-static/public/ .
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            ./static-js-builder.tar.gz
            ./static.tar.gz
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: ${{ github.event.release.tag_name }}
      #   with:
      #     name: artifacts
      #     draft: true
      #     files: ./target/*${{ github.event.release.tag_name }}*
