name: Build artifacts

on:
  # release:
  #   types: [published]
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:
  build-static:
    runs-on: ubuntu-latest
    container: clojure:lein
    steps:
      - uses: actions/checkout@v2
      - name: install os deps
        run: |
          apt-get -qq update && apt-get -qy install rpm fakeroot
      - name: install lein deps
        run: |
          lein install
      - name: install nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - name: install node.js
        run: |
          . "$NVM_DIR/nvm.sh" && nvm install v19.6.1
        env:
          NVM_DIR: $HOME/.nvm
      - name: get node deps
        run: |
          . "$NVM_DIR/nvm.sh" && npm install
        env:
          NVM_DIR: $HOME/.nvm
      - name: build static - clj->js (js builder script)
        run: |
          . "$NVM_DIR/nvm.sh" && lein cljsbuild once prerender
        env:
          NVM_DIR: $HOME/.nvm
      - name: build static - js->html
        run: |
          . "$NVM_DIR/nvm.sh" && node target/cljsbuild/prerender/main.js target/cljsbuild/prod-static/public/
        env:
          NVM_DIR: $HOME/.nvm
      - name: make archive - js builder script
        run: |
          tar -czvf static-js-builder-${{ github.ref_name }}.tar.gz -C target/cljsbuild/prerender/ .
      - name: make archive - js builder script (unversioned)
        run: |
          tar -czvf static-js-builder.tar.gz -C target/cljsbuild/prerender/ .
      - name: make archive - static site
        run: |
          tar -czvf static-${{ github.ref_name }}.tar.gz -C target/cljsbuild/prod-static/public/ .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.ref_name }}
          path: |
            ./*.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: ${{ github.event.release.tag_name }}
        with:
          name: ${{ github.ref_name }}
          draft: true
          files: ./*${{ github.ref_name }}*.tar.gz
